### ISSUE TITLE
Data Merge Indesign Template and Tutorial

### ISSUE THREAD

**Issue by lucagitent** [grefel/indesignjs-resources#4]
https://pagination.com/tutorials/data-merge-indesign/

**Comment by ff6347** [comment]
@lucagitent are you trying to promote your application?

**Comment by lucagitent** [comment]
Hi @fabianmoronzirfas ! The tutorial and free template are one of the most complete and refined you can find on Internet, and it is helping many people to independently start the path to advance InDesign features. To me it seems to fit into http://grefel.github.io/indesignjs-resources/, so I proposed. No hard feeling if you decided not. Maybe the XML template and tutorial that will be soon available for free it will be even a better fit.

**Comment by grefel** [comment]
thanks for the link, but i keep the list clean with scripting resources. Nice tutorial I promote it via twitter anyway! Keep me updated with the XML-Tutorial.
